[package]
name = "advent_of_code"
version = "1.0.0"
authors = ["Danny Foster <danny@foster.sh>"]
edition = "2021"
default-run = "advent_of_code"
publish = false

[lib]
doctest = false

[features]
test_lib = []

[dependencies]
itertools = "0.12.0"
pico-args = "0.5.0"
regex = "1.10.2"
